### ISSUE TITLE
AoC 2022

### ISSUE THREAD

**Issue by Silver-Golden** [nuoxoxo/advent-of-code#12]
Hi there,

Are you a member of UL comsoc?  
Saw yer entry on our leaderboard but cannot find ye in our discord.

Brendan.

**Comment by nuoxoxo** [comment]
Hi Mr Brendan. No I'm not a member I think I've just stumbled upon a private board code and wanted to see how other people are doing. 
It's the comsoc board right, i can quit if you want?

**Comment by Silver-Golden** [comment]
How did you stumble across it?

**Comment by nuoxoxo** [comment]
> How did you stumble across it?

<details><summary>that's how</summary>

![](https://i.imgur.com/HGSCvJO.png)
</details>

**Comment by Silver-Golden** [comment]
Thanks, we will fix that in the future.

Would you remove yerself from teh list?

**Comment by Silver-Golden** [comment]
Also do you think it is a good idea to join private leaderboards without being invited?
