### ISSUE TITLE
Netsoc Advent Of Code 3rd Place Prize

### ISSUE THREAD

**Issue by ash-xyz** [nuoxoxo/advent-of-code#2]
Hi @nuoxoxo,

You claimed 3rd place in our private leaderboard for AOC, if you're a UCD student please reach out to me on our [Discord ](https://discord.netsoc.com) under the #coding-competitions so I can give you your prize.

**Comment by nuoxoxo** [comment]
@ash-xyz Thank you but sorry, I'm not a student of UCD.
